import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';

const source = readFileSync(path.resolve(import.meta.dirname, 'AuthShell.tsx'), 'utf8');
const loginSource = readFileSync(path.resolve(import.meta.dirname, '..', 'pages', 'Login.tsx'), 'utf8');
assert.match(source, /max-lg:bg-\[#efebf6\]/);
assert.match(source, /max-lg:pt-\[65px\]/);
assert.match(source, /max-lg:max-w-\[366px\]/);
assert.match(source, /max-lg:h-12[\s\S]*max-lg:rounded-\[8px\]/);
assert.doesNotMatch(source, /shadow-feature/);
assert.match(source, /desktopLayout\?: 'default' \| 'centered-card'/);
assert.match(source, /desktop-auth-main/);
assert.match(source, /desktop-auth-card/);
assert.match(source, /desktopOnboarding \? 'lg:flex-row/, 'Desktop onboarding should use one adaptive layout from 1024px upward');
assert.match(source, /lg:w-\[clamp\(/, 'Desktop onboarding sidebar should scale fluidly between 1024px and 1440px');
assert.match(source, /lg:min-w-0[\s\S]*lg:flex-1/, 'Desktop auth main should remain shrink-safe at intermediate widths');
assert.doesNotMatch(source, /min-\[1440px\]|fallback/, 'AuthShell must not retain an intermediate-width fallback implementation');
assert.doesNotMatch(loginSource, /mobileHeaderMode="status-aware"/);
assert.doesNotMatch(loginSource, /mobileProgress=/);
assert.doesNotMatch(loginSource, /hideMobileLeadingIconWhenFilled/);
assert.match(source, /max-lg:size-11/);
assert.match(loginSource, /mobileFieldLayout="figma-auth"/);
assert.match(loginSource, /mobileVisual="figma-auth"/);
assert.match(loginSource, /to="\/onboarding"/);
assert.doesNotMatch(loginSource, /to="\/register"/);
