from enum import Enum


class UserErrorCode(str, Enum):
    USERNAME_IS_EMPTY = "USERNAME_IS_EMPTY"
    USERNAME_TOO_SHORT = "USERNAME_TOO_SHORT"
    USERNAME_TOO_LONG = "USERNAME_TOO_LONG"
    USERNAME_INVALID_CHARACTERS = "USERNAME_INVALID_CHARACTERS"
    USERNAME_INVALID_EDGE_SYMBOL = "USERNAME_INVALID_EDGE_SYMBOL"
    USERNAME_REPEATED_SYMBOLS = "USERNAME_REPEATED_SYMBOLS"

    EMAIL_IS_EMPTY = "EMAIL_IS_EMPTY"
    EMAIL_INVALID = "EMAIL_INVALID"
    EMAIL_TOO_LONG = "EMAIL_TOO_LONG"
