import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const src = fs.readFileSync(path.resolve(import.meta.dirname, 'TermCard.tsx'), 'utf8');
const previewSrc = fs.readFileSync(path.resolve(import.meta.dirname, 'MeasuredTextPreview.tsx'), 'utf8');

assert.doesNotMatch(src, /inspectMode|interactionMode|onInspect/, 'TermCard should not retain the removed inspectMode compatibility prop');
assert.match(src, /expansion\?: ['"]intrinsic['"] \| ['"]fill-parent['"]/, 'TermCard should expose intrinsic and fill-parent expansion modes');
assert.match(src, /expansion = ['"]intrinsic['"]/, 'TermCard expansion must default to intrinsic');
assert.match(src, /truncate/, 'TermCard titles must use single-line ellipsis overflow');
assert.match(src, /gap-12/, 'TermCard title/actions row must preserve the exact 48px horizontal gap');
assert.match(src, /text-\[#8C8698\]/i, 'TermCard definition preview must use the canonical muted definition color');
assert.match(src, /data-term-card-state|data-state/, 'desktop card states should be inspectable');
assert.match(src, /Hover|Clicked|selected/, 'desktop card should expose default, hover/focus and clicked states');
assert.match(src, /w-\[716px\]/, 'hover state should add the 32px purple rail to the 684px card');
assert.match(src, /hover:w-\[716px\]|focus-within:w-\[716px\]/, 'wrapper must expand from its own hover/focus state');
assert.match(src, /w-\[951px\]/, 'clicked state should reserve 684px main plus 266px source panel');
assert.match(src, /fill-parent[\s\S]*w-full|w-full[\s\S]*fill-parent/, 'fill-parent selected cards should fill the available results rail');
assert.match(src, /min-w-0 flex-1[\s\S]*data-term-card-source-panel|data-term-card-source-panel[\s\S]*min-w-0 flex-1/, 'fill-parent source panel should flex to the right edge');
assert.match(src, /max-\[1131px\]:flex-wrap/, 'fill-parent selected cards should stack while the fixed sidebar narrows the main column');
assert.match(src, /max-\[1131px\]:basis-full[\s\S]*max-\[1131px\]:w-full/, 'narrow stacked source panel should fit the available main-column width');
assert.match(src, /w-full max-w-\[684px\]/, 'collapsed card main should shrink fluidly and cap at 684px');
assert.match(src, /h-\[208px\]/, 'desktop card should preserve the Figma 208px vertical anatomy');
assert.doesNotMatch(src, /data-term-card-main[^\n]*overflow-hidden|data-term-card-body[^\n]*overflow-hidden/, 'inspect anatomy should not rely on structural clipping');
assert.match(src, /MeasuredTextPreview/, 'inspect definition should use the measured reusable preview');
assert.match(src, /maxHeight=\{80\}/, 'inspect definition viewport should cap at 80px');
assert.match(src, /min-h-\[208px\] h-auto/, 'long inspect content should grow while short cards retain a 208px minimum');
assert.match(src, /flex[^\"]*flex-col gap-4/, 'inspect body should group header and definition with a 16px gap');
assert.match(src, /data-term-card-body/, 'inspect body should be explicitly grouped');
assert.match(src, /data-term-card-main/, 'inspect main card should be explicitly identified');
assert.match(src, /flex[^\"]*flex-col gap-8/, 'main card should keep one outer 32px gap around the body and CTA');
assert.match(src, /py-8[\s\S]*data-term-card-rail/, 'hover rail should have 32px vertical inset around its centered inner rail');
assert.match(src, /self-stretch[^\"]*w-8[\s\S]*data-term-card-rail/, 'hover rail wrapper should stretch to the natural main card height');
assert.match(src, /h-full[^\"]*w-8[^\"]*[^>]*data-term-card-rail/, 'hover rail control should fill the stretched rail minus its 32px insets');
assert.match(src, /data-term-card-source-panel/, 'clicked source panel should remain explicitly inspectable');
assert.match(src, /self-stretch[^\"]*w-\[266px\][^>]*data-term-card-source-panel/, 'clicked source panel should stretch to the natural main card height');
assert.doesNotMatch(src, /data-term-card-rail[^\"]*h-\[208px\]|data-term-card-source-panel[^\"]*h-\[208px\]/, 'rail and source panel must not pin themselves to the short-card height');
assert.doesNotMatch(src, /data-term-card-main[\s\S]*gap-8[\s\S]*data-term-card-header-actions[\s\S]*max-h-\[80px\][\s\S]*gap-8/, 'inspect header, definition and CTA must not be three flattened gap-32 siblings');
assert.doesNotMatch(src.slice(src.indexOf('inspectMode ?'), src.indexOf(') : (')), /[\u0400-\u04ff]/, 'inspect branch must not hard-code Cyrillic copy');
assert.match(src, /t\('terms\.inspectDetailsCta'\)/, 'inspect CTA should use i18n');
assert.match(src, /t\('terms\.inspectSourceTitle'\)/, 'inspect source title should use i18n');
assert.match(src, /text-\[22px\] leading-6/, 'short inspect titles should reserve a 24px line box so descenders are not clipped');
assert.match(src, /text-\[20px\] leading-5/, 'long inspect titles should use the permitted compact 20/20 typography');
assert.doesNotMatch(src, /max-w-\[760px\][\s\S]*text-\[15px\]/, 'TermCard should not retain the removed legacy branch');
assert.match(src, /p-6/, 'desktop card should use 24px padding');
assert.match(src, /gap-8/, 'desktop card should use a 32px internal gap');
assert.match(src, /w-\[216px\].*h-10|h-10.*w-\[216px\]/, 'desktop CTA should be 216x40');
assert.match(src, /size-6|size=\{24\}/, 'desktop directional controls should expose 24px hit targets');
assert.match(src, /data-term-card-header-actions[\s\S]*<TermCardFavoriteButton/, 'header actions should keep flag and local favorite together as siblings');
assert.match(src, /className="[^"]*gap-4[^"]*"[^>]*data-term-card-header-actions/, 'header actions should preserve the explicit 16px gap');
assert.match(src, /TermCardFavoriteButton[^\n]*termRef=\{term\.public_id\}/, 'inspect branch must use the local favorite control');
assert.match(src, /<button[\s\S]*aria-label=\{term\.name\}/, 'inspect title toggle must remain a separate native button');
assert.match(src, /const detailLink = <Link/, 'detail navigation must remain a separate native link');
assert.match(src, /source-panel|DefinitionMetadata[^\n]*variant=["']source-panel/, 'clicked state should render the named source-panel metadata variant');
assert.match(src, /ArrowRight01Icon|ArrowLeft01Icon/, 'hover and clicked states should use directional HugeIcons');
assert.match(src, /focus-visible/, 'hover information should be keyboard accessible');
assert.match(src, /data-term-card-header-actions[\s\S]*<TermCardFavoriteButton/, 'canonical header actions must keep the local favorite control');
assert.match(src, /const detailLink = <Link[\s\S]*<\/Link>/, 'inspect branch must retain a native detail link');
assert.match(previewSrc, /Math\.round\(node\.scrollHeight \/ lineHeight\)/, 'preview overflow must round measured visible lines');
assert.match(previewSrc, /Math\.round\(maxHeight \/ lineHeight\)/, 'preview overflow must round the allowed line count');
assert.ok(Math.round(83 / 16) <= Math.round(80 / 16), '83px Chromium surplus must fit within an 80px five-line preview');
assert.ok(Math.round(99 / 16) > Math.round(80 / 16), '99px six-line content must overflow an 80px preview');

console.log('Desktop TermCard state contract passed');
