import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const source = fs.readFileSync(path.resolve(import.meta.dirname, 'TermSearchPage.tsx'), 'utf8');
const storySource = fs.readFileSync(path.resolve(import.meta.dirname, 'TermSearchPage.stories.tsx'), 'utf8');
const desktopNotFoundStory = storySource.match(/export const DesktopNotFound:[\s\S]*?(?=\nexport const |$)/)?.[0] ?? '';

assert.match(source, /w-full max-w-\[684px\]/, 'desktop search rails should shrink fluidly and cap at the 684px Figma width');
assert.match(source, /min-\[1132px\]:w-\[400px\]/, 'desktop search input should restore exactly 400px when the Figma rail fits');
assert.match(source, /w-\[125px\].*#ded2f1|#ded2f1.*w-\[125px\]/s, 'desktop filter control should be 125px lavender');
assert.match(source, /w-\[143px\].*#572d9f|#572d9f.*w-\[143px\]/s, 'desktop submit control should be 143px purple');
assert.match(source, /hidden [^"\n]*flex-col gap-4 md:flex[\s\S]*<TermCard/, 'desktop result list should use TermCard');
assert.doesNotMatch(source, /inspectMode|interactionMode|onInspect/, 'search results should use the canonical TermCard API');
assert.match(source, /featured.*loading|featured.*error|search.*error|retry/i, 'desktop page should render explicit loading/error/retry states');
assert.match(source, /type="button"[\s\S]*onClick=\{\(\) => setFiltersOverlayRequest\(null\)\}/, 'desktop filters must open a local full overlay');
assert.doesNotMatch(source, /data-desktop-search-controls[\s\S]*<Link/, 'desktop filters must not navigate away from the search page');
assert.match(source, /onSubmit=\{[\s\S]*submitSearch/, 'desktop search submit must execute the normalized query');
assert.match(source, /search\.sheetClose[\s\S]*Cancel01Icon/, 'desktop filter dialog should expose a visible accessible close control');
assert.match(source, /data-desktop-search-modes/, 'desktop search should render a stable mode rail');
assert.match(source, /data-search-mode=\{item\.value\}/, 'search modes should expose a shared stable mode selector');
assert.match(source, /useState<['"]random['"] \| ['"]forYou['"] \| ['"]popular['"]>\(['"]random['"]\)/, 'desktop mode rail should default to Random');
assert.match(source, /modeRandom[\s\S]*modeForYou[\s\S]*modePopular/, 'desktop mode rail should expose Random, For You, and Popular labels');
assert.match(source, /mt-8|margin-top:32px/, 'desktop controls should reserve 32px before mode rail');
assert.match(source, /gap-2/, 'desktop mode pills should use an 8px gap');
assert.match(source, /data-desktop-search-results/, 'desktop result states should share a stable results selector');
assert.match(source, /data-desktop-search-load-more/, 'desktop load-more should expose a stable selector');
assert.match(source, /data-desktop-search-load-more[\s\S]*h-12[\s\S]*w-full max-w-\[684px\][\s\S]*bg-\[#ded2f1\]/, 'desktop load-more should shrink fluidly while preserving the 684x48 Figma maximum and lavender surface');
assert.match(source, /query\.trim\(\)/, 'desktop controls should branch immediately on the raw trimmed query');
assert.match(source, /data-desktop-search-filters/, 'desktop typed search should render a stable quick-filter rail');
assert.match(source, /onOpenFilter=\{\(filterId\) => setFiltersOverlayRequest\(filterId\)\}/, 'desktop category chips should request an in-place category popup');
assert.doesNotMatch(source, /<Link[\s\S]*data-desktop-search-filter/, 'desktop category chips must not be route links');
assert.match(source, /data-desktop-search-filter/, 'desktop quick filters should expose stable chip selectors');
assert.match(source, /getSearchResultFilterChips/, 'desktop quick filters should reuse the shared result-filter view model');
assert.match(source, /overflow-x-auto/, 'desktop quick filters should preserve responsive horizontal overflow');
assert.match(source, /Cancel01Icon/, 'active desktop quick filters should use the Figma cancel HugeIcon');
assert.match(source, /min-w-0/, 'desktop search flex geometry should allow narrow main columns to shrink');
assert.match(source, /type="text"[\s\S]*inputMode="search"/, 'desktop search input should use text/search semantics without browser native clear affordance');
assert.match(source, /text-\[16px\] leading-\[16px\]/, 'desktop search input typography should use the Figma 16px/16px pair');
assert.match(source, /data-desktop-search-clear[\s\S]*Cancel01Icon/, 'desktop search should expose the custom HugeIcons clear affordance');
assert.match(source, /query\.length > 0/, 'desktop clear affordance should only render for a non-empty query');
assert.match(source, /data-desktop-search-not-found[\s\S]*variant="outcome"/, 'desktop not-found should reuse the outcome EmptyState variant');
assert.match(source, /data-empty-state-icon|size-16 size-16 rounded-full bg-\[#ded2f1\]/, 'desktop not-found icon circle should expose deterministic Figma geometry and paint');
assert.match(source, /data-desktop-search-query-heading[\s\S]*notFoundHeading[\s\S]*debounced\.trim\(\)/, 'desktop not-found heading should use localized settled trimmed query copy');
assert.match(source, /data-desktop-search-query-heading[^>]*className="[^"]*w-full[^\"]*self-start[^\"]*text-left/, 'desktop not-found heading should fill and left-align the 684px rail');
assert.match(source, /<label htmlFor="desktop-search-input"[\s\S]*<input[\s\S]*id="desktop-search-input"/, 'desktop search input should have an explicit accessible label without nesting the clear button');
assert.doesNotMatch(source, /<label className="relative flex h-10/, 'desktop search controls must not nest an interactive clear button inside a label');
assert.match(source, /text-\[#161519\]/, 'desktop query heading should use the approved Figma text color');
assert.match(source, /notFoundTitle|notFoundDescription/, 'desktop not-found should use dedicated localized copy');
assert.doesNotMatch(source, /data-adaptive-outcome-desktop[\s\S]*HelpCircleIcon/, 'desktop not-found must not render the legacy help-circle empty state');
assert.notEqual(desktopNotFoundStory, '', 'DesktopNotFound story should remain present');
assert.doesNotMatch(desktopNotFoundStory, /a11y\s*:\s*\{\s*disable\s*:\s*true\s*\}/, 'DesktopNotFound must keep a11y checks enabled');
assert.match(source, /data-desktop-search-content/, 'desktop search content should expose a stable geometry selector');
assert.match(source, /md:px-\[10px\]/, 'narrow desktop search should use 10px horizontal gutters');
assert.match(source, /min-\[1132px\]:px-16/, 'desktop search should restore 64px gutters once the full rail fits');

console.log('Desktop TermSearch Figma contract passed');
