import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const appSource = fs.readFileSync(path.join(root, 'App.tsx'), 'utf8');
const pageSource = fs.readFileSync(path.join(root, 'pages', 'PracticeByTopicPage.tsx'), 'utf8');
const viewSource = fs.readFileSync(path.join(root, 'features', 'tests', 'components', 'PracticeByTopicView.tsx'), 'utf8');
const analyzeSource = fs.readFileSync(path.join(root, 'pages', 'Analyze.tsx'), 'utf8');
const weightedChipSource = viewSource.slice(viewSource.indexOf('function WeightedQuestionChip'));

assert.match(appSource, /path="\/practice-by-topic"[\s\S]*<PracticeByTopicPage \/>/);
assert.match(analyzeSource, /to=\{`\/practice-by-topic\?chapterId=/);
assert.match(viewSource, /Практика по разделу/);
assert.match(viewSource, /chapterTitle/);
assert.match(viewSource, /bg-\[#efebf6\]/);
assert.match(viewSource, /bg-white[\s\S]*rounded-\[8px\]/);
assert.match(viewSource, /CheckmarkCircle02Icon/);
assert.match(viewSource, /PlayIcon/);
assert.match(viewSource, /CircleIcon/);
assert.match(viewSource, /text-\[14px\] font-normal leading-\[14px\] text-\[#39363f\]/);
assert.match(viewSource, /text-\[12px\] font-medium leading-\[12px\] text-\[#6a37c3\]/);
assert.match(viewSource, /leading-\[16px\]|leading-none/);
assert.match(viewSource, /gap-x-4[\s\S]*\[&>h1\]:!text-\[16px\][\s\S]*\[&>h1\]:!leading-4/);
assert.match(pageSource, /tests\/default\?topicCode/);
assert.match(pageSource, /selectAnalyzeResultAccess\(results\)/);
assert.match(pageSource, /access\.freeChapter\?\.chapter_id === requestedChapterId/);
assert.match(pageSource, /createUnavailableData\('loading'\)/);
assert.match(pageSource, /createUnavailableData\('unavailable'\)/);
assert.match(pageSource, /useState<AnalyzeChapterResult\[\] \| null \| undefined>\(undefined\)/);
assert.match(pageSource, /results === undefined\) return createUnavailableData\('loading'\)/);
assert.match(pageSource, /results === null\) return createUnavailableData\('unavailable'\)/);
assert.match(pageSource, /\.catch\(\(\) => active && setResults\(null\)\)/);
assert.doesNotMatch(pageSource, /fallbackData|Веб-проектирование|index === 0|Math\.min\(2/);
assert.match(pageSource, /window\.history\.length[\s\S]*navigate\(-1\)/);
assert.match(pageSource, /navigate\('\/analyze', \{ replace: true \}\)/);
assert.match(pageSource, /firstAvailableTopicIndex/);
assert.match(pageSource, /status: isTopicCompleted\(topic\)/);
assert.match(pageSource, /: index === firstAvailableTopicIndex/);
assert.doesNotMatch(pageSource, /status: 'active' as const/);
assert.match(pageSource, /topic\.status === 'completed'/);
assert.match(pageSource, /topic\.progress >= 100/);
assert.match(pageSource, /weightedQuestionCount: Math\.max\(0, chapter\.max_score - chapter\.question_count\)/);
assert.match(pageSource, /completedPercent: 0/);
assert.match(viewSource, /practiceByTopic\.completed/);
assert.match(viewSource, /aria-label=\{t\('practiceByTopic\.progressLabel'/);
assert.match(viewSource, /<Progress[\s\S]*size="md"[\s\S]*trackClassName="!rounded-\[8px\] !bg-\[rgba\(106,55,195,0\.25\)\]"[\s\S]*indicatorClassName="!rounded-\[8px\] !bg-\[#6a37c3\]"/);
assert.match(viewSource, /data\.weightedQuestionCount > 0/);
assert.match(weightedChipSource, /type="button"[\s\S]*ref=\{buttonRef\}[\s\S]*onFocus=\{updateTooltipPosition\}/);
assert.match(weightedChipSource, /aria-label=\{t\('practiceByTopic\.weightedQuestionHelpLabel'/);
assert.match(weightedChipSource, /aria-describedby=\{tooltipId\}/);
assert.match(weightedChipSource, /role="tooltip"/);
assert.match(weightedChipSource, /group-focus-visible:opacity-100/);
assert.match(weightedChipSource, /weightedQuestionTooltip/);

console.log('Practice by topic Figma mobile contract passed.');
