import assert from 'node:assert/strict';
import { existsSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
const dir = import.meta.dirname;
const source = readFileSync(path.resolve(dir, 'Subscription.tsx'), 'utf8');
const story = readFileSync(path.resolve(dir, 'Subscription.stories.tsx'), 'utf8');
const app = readFileSync(path.resolve(dir, '../App.tsx'), 'utf8');
const profile = readFileSync(path.resolve(dir, 'Profile.tsx'), 'utf8');
assert.match(source, /MobilePageFrame[\s\S]*scrollMode="content" safeAreaBottom=\{false\} contentClassName="!pt-\[26px\]"/);
assert.doesNotMatch(source, /\bfooter(?:ClassName)?=/, 'Subscription actions must remain inside the scrollable main flow');
assert.match(source, /title:\s*<span className="text-\[16px\] font-medium leading-\[16px\] text-\[#252329\]">\{t\('profile\.subscriptionTitle'\)\}<\/span>/);
assert.match(source, /navigate\('\/profile'\)/);
assert.match(source, /function SubscriptionPlanCard/);
assert.match(source, /type="radio"/);
assert.match(source, /ArrowLeft01Icon[\s\S]*CheckIcon[\s\S]*Tick02Icon[\s\S]*from '@hugeicons\/core-free-icons';/);
assert.match(source, /selected && <HugeiconsIcon icon=\{CheckIcon\} size=\{14\} \/>/);
assert.doesNotMatch(source, /selected && <HugeiconsIcon icon=\{CheckIcon\} \/>/);
assert.doesNotMatch(source, /✓/);
assert.doesNotMatch(source, /selected && <span className="text-\[14px\] leading-none">/);
assert.doesNotMatch(source, /ChoiceGroup|RadioOption/);
assert.match(source, /useState<Plan>\('annual'\)/);
assert.match(source, /<\/section>\s*<div data-subscription-actions className="mx-auto mt-6 w-full max-w-\[430px\] px-6 pb-4">/, 'CTA wrapper must immediately follow the card in main flow with a 24px gap');
assert.match(source, /data-subscription-cta[\s\S]*<\/button><p data-subscription-disclosure className="mt-4 text-center text-\[12px\]/, 'Disclosure must directly follow the CTA with a 16px gap');
assert.match(source, /<li key=\{key\} className="flex items-center gap-2 text-left text-\[12px\] leading-\[12px\] text-\[#6E6779\]">/);
for (const text of ['2490₸', '9900₸', '-67%', '#EFEBF6', '#252329', '#A585DB', '#F8F5FC', '#DED2F1', '#EFEAF8', '#6A37C3']) assert.match(source, new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
assert.doesNotMatch(source, /-60%/);
assert.doesNotMatch(source, /1490|17880|−40|Infopedia Premium/);
assert.equal((source.match(/h-px w-full bg-\[#EFEAF8\]/g) ?? []).length, 3);
const timelineTodayPath = path.resolve(dir, '../assets/figma-subscription/timeline-today.svg');
assert.ok(existsSync(timelineTodayPath)); assert.ok(statSync(timelineTodayPath).size > 500); assert.match(source, /timeline-today\.svg/);
assert.match(source, /CreditCardIcon[\s\S]*Notification01Icon/);
assert.match(source, /size-6[\s\S]*rounded-full[\s\S]*bg-\[#EFEAF8\][\s\S]*icon=\{CreditCardIcon\}[\s\S]*size=\{14\}/);
assert.match(source, /size-6[\s\S]*rounded-full[\s\S]*bg-\[#EFEAF8\][\s\S]*icon=\{Notification01Icon\}[\s\S]*size=\{14\}/);
assert.doesNotMatch(source, /timeline-day-6\.svg|timeline-day-7\.svg|timelineDay6|timelineDay7/);
assert.doesNotMatch(source, /https:\/\/www\.figma\.com\/api\/mcp\/asset/);
for (const key of ['subscriptionPurchase', 'subscriptionPremiumTitle', 'subscriptionTimelineToday', 'subscriptionTimelineDay6', 'subscriptionTimelineDay7', 'subscriptionBenefitsEyebrow', 'subscriptionBenefitPlan', 'subscriptionBenefitTests', 'subscriptionBenefitTopics']) assert.match(source, new RegExp(key));
assert.match(source, /aria-live="polite"/); assert.doesNotMatch(source, /fetch\(|axios\.|localStorage|sessionStorage/);
assert.match(app, /path="\/subscription"[\s\S]*<Protected>[\s\S]*<Subscription\s*\/>/); assert.match(profile, /navigate\('\/subscription'\)/);
assert.match(source, /data-subscription-desktop/);
for (const marker of ['subscriptionDesktopHeading', 'subscriptionDesktopFeatureSearchTitle', 'subscriptionDesktopFeatureTestsTitle', 'subscriptionDesktopFeatureAnalyzeTitle', 'subscriptionDesktopPlanHeading', 'subscriptionDesktopCta']) {
  assert.match(source, new RegExp(marker));
}
for (const icon of ['SearchingIcon', 'CheckmarkSquare02Icon', 'PieChart02Icon', 'Tick02Icon']) assert.match(source, new RegExp(icon));
assert.match(source, /data-subscription-desktop-cta[^>]*disabled/);
assert.doesNotMatch(source, /data-subscription-desktop-cta[^>]*onClick/);
assert.match(source, /data-subscription-desktop-cta[^>]*hover:bg-action-primary-hover/);
assert.match(source, /data-subscription-desktop-cta[^>]*disabled:cursor-not-allowed/);
assert.match(source, /subscriptionDesktopCtaMonthly/);
assert.match(source, /subscriptionDesktopCtaAnnual/);
assert.match(source, /plan === 'annual' \? t\('profile\.subscriptionDesktopCtaAnnual'\) : t\('profile\.subscriptionDesktopCtaMonthly'\)/);
assert.doesNotMatch(source, /t\('profile\.subscriptionDesktopCta'\)/);
assert.match(source, /name="subscription-desktop-plan"/);
assert.match(source, /<fieldset className="flex min-w-0 flex-col gap-4 border-0 p-0">[\s\S]*<legend className="sr-only">\{t\('profile\.subscriptionPlanLabel'\)\}<\/legend>/);
assert.match(source, /data-subscription-desktop-back/);
assert.match(source, /aria-label=\{t\('common\.previous'/);
assert.match(source, /window\.history\.state\?\.idx/);
assert.match(source, /typeof historyIndex === 'number' && historyIndex > 0/);
assert.doesNotMatch(source, /window\.history\.length/);
assert.match(source, /navigate\(-1\)/);
assert.match(source, /navigate\('\/profile', \{ replace: true \}\)/);
assert.match(source, /text-\[#6A37C3\]/);
for (const token of ['cursor-pointer', '!text-[#6A37C3]', 'hover:!bg-[#f8f5fc]', 'hover:!text-[#6A37C3]', 'focus-visible:!bg-[#f8f5fc]', 'focus-visible:!text-[#6A37C3]', 'focus-visible:!ring-[#6A37C3]', 'focus-visible:!ring-offset-[#efeaf8]', 'transition-[background-color,color,box-shadow]', 'duration-[140ms]', 'motion-reduce:transition-none']) assert.match(source, new RegExp(token.replace(/[\[\]#(),:-]/g, '\\$&')));
assert.match(source, /text-\[24px\] font-medium/);
assert.match(source, /text-\[16px\] font-normal/);
assert.match(story, /BrowserRouter/);
assert.match(story, /configureBrowserHistory/);
assert.match(story, /data-subscription-back-target/);
assert.match(story, /DesktopBackDirectEntry/);
assert.match(story, /DesktopBackHoverAndKeyboardFocus/);
assert.match(story, /DesktopAnnualCtaHover/);
assert.match(story, /DesktopMonthlyCtaHover/);
assert.match(story, /Desktop1440x1080MonthlySelected[\s\S]*withBrowserHistory\('prior'\)/);
assert.match(story, /Desktop1024AdaptiveGeometry/);
assert.match(story, /Desktop1280AdaptiveGeometry/);
assert.match(source, /className="hidden[^\"]*md:flex/);
assert.match(source, /data-subscription-desktop className="hidden relative min-h-screen[^"]*md:items-start[^"]*md:px-8[^"]*md:pb-8[^"]*md:pt-24[^"]*lg:items-center[^"]*lg:py-16[^"]*xl:px-16[^"]*min-\[1440px\]:px-32/);
assert.match(source, /data-subscription-desktop-row className="grid w-full max-w-\[1184px\] min-w-0 grid-cols-1 gap-4 lg:grid-cols-2"/);
assert.match(source, /data-subscription-desktop-left className="[^"]*flex[^"]*flex-col[^"]*items-start[^"]*justify-between/);
assert.match(source, /data-subscription-desktop-left className="[^"]*min-h-\[551px\][^"]*p-8[^"]*xl:p-12[^"]*min-\[1440px\]:p-16/);
assert.match(source, /data-subscription-desktop-right className="[^"]*min-h-\[551px\][^"]*p-8[^"]*xl:p-12[^"]*min-\[1440px\]:p-16/);
assert.doesNotMatch(source, /px-\[clamp\(|p-\[clamp\(/, 'Desktop geometry must use exact breakpoint values instead of fluid interpolation');
assert.match(source, /data-subscription-desktop-feature className="[^"]*items-center[^"]*gap-6/);
assert.match(source, /selected\s*\? 'h-\[72px\] bg-\[#F8F5FC\] py-4'\s*:\s*'h-\[72px\] border-\[1\.5px\] border-\[#F8F5FC\] py-4'/);
assert.match(source, /data-subscription-desktop-plan=\{value\}[\s\S]*items-center justify-between gap-6 rounded-\[16px\] px-6/);
assert.doesNotMatch(source, /h-\[(?:80|84)px\]|py-5/);
assert.match(source, /function SubscriptionPlanCard[\s\S]*h-\[108px\]/);
assert.match(source, /rounded-\[8px\] bg-\[#DED2F1\][^\"]*px-2 py-0\.5 text-\[14px\] leading-\[14px\] text-\[#6A37C3\]/);
assert.match(source, /data-subscription-contrast-lock="annual-equivalent"/);
for (const sourcePair of ['mobile-supporting-copy', 'mobile-plan-price', 'mobile-plan-meta', 'mobile-discount', 'mobile-disclosure']) {
  assert.match(source, new RegExp(`data-subscription-contrast-lock="${sourcePair}"`));
}
assert.match(story, /export const Mobile430Geometry:[\s\S]*selector: '\*:not\(\[data-subscription-contrast-lock\]\)'[\s\S]*play:/);
assert.doesNotMatch(story, /id: 'color-contrast'[\s\S]{0,120}(?:enabled:\s*false|disable:\s*true)/, 'Source color exception must remain selector-scoped');
assert.match(source, /data-subscription-desktop-cta[\s\S]*text-\[18px\][\s\S]*leading-\[18px\]/);
for (const localeName of ['ru', 'kk']) { const raw = readFileSync(path.resolve(dir, `../locales/${localeName}/translation.json`), 'utf8'); const keys = [...raw.matchAll(/^\s+"(subscription[A-Za-z0-9]+)"\s*:/gm)].map(m => m[1]); assert.equal(keys.length, new Set(keys).size, `${localeName} duplicate subscription keys`); assert.match(raw, /"subscriptionDiscount": "-67%"/); assert.doesNotMatch(raw, /"subscriptionDiscount": "-60%"/); assert.doesNotMatch(raw, /"subscriptionDesktopCta"\s*:/); for (const key of ['subscriptionDesktopHeading', 'subscriptionDesktopSubtitle', 'subscriptionDesktopFeatureSearchTitle', 'subscriptionDesktopFeatureTestsTitle', 'subscriptionDesktopFeatureAnalyzeTitle', 'subscriptionDesktopPlanHeading', 'subscriptionDesktopPlanSubtitle', 'subscriptionDesktopCtaMonthly', 'subscriptionDesktopCtaAnnual']) assert.match(raw, new RegExp(`"${key}"\\s*:\\s*"[^"].+"`)); }
const ruLocale = readFileSync(path.resolve(dir, '../locales/ru/translation.json'), 'utf8');
assert.match(ruLocale, /"subscriptionDesktopHeading": "Готовься с нами"/);
assert.match(ruLocale, /"subscriptionDesktopCtaMonthly": "Оформить Premium на месяц"/);
assert.match(ruLocale, /"subscriptionDesktopCtaAnnual": "Оформить Premium на год"/);
const kkLocale = readFileSync(path.resolve(dir, '../locales/kk/translation.json'), 'utf8');
assert.match(kkLocale, /"subscriptionDesktopCtaMonthly": "Premium-ды бір айға рәсімдеу"/);
assert.match(kkLocale, /"subscriptionDesktopCtaAnnual": "Premium-ды бір жылға рәсімдеу"/);
console.log('Subscription contract passed');
