import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

const page = readFileSync(path.resolve(import.meta.dirname, 'Tests.tsx'), 'utf8');
const viewPath = path.resolve(import.meta.dirname, '../features/tests/components/DesktopTestsHubView.tsx');
const view = existsSync(viewPath) ? readFileSync(viewPath, 'utf8') : '';
const optionCard = readFileSync(path.resolve(import.meta.dirname, '../features/tests/components/DesktopTestOptionCard.tsx'), 'utf8');
const chapterCard = readFileSync(path.resolve(import.meta.dirname, '../features/tests/components/DesktopChapterTestCard.tsx'), 'utf8');
const story = readFileSync(path.resolve(import.meta.dirname, '../features/tests/components/TestsHubView.stories.tsx'), 'utf8');
const optionStoryPath = path.resolve(import.meta.dirname, '../features/tests/components/DesktopTestOptionCard.stories.tsx');
const optionStory = existsSync(optionStoryPath) ? readFileSync(optionStoryPath, 'utf8') : '';
const chapterStoryPath = path.resolve(import.meta.dirname, '../features/tests/components/DesktopChapterTestCard.stories.tsx');
const chapterStory = existsSync(chapterStoryPath) ? readFileSync(chapterStoryPath, 'utf8') : '';
const dashboardModel = readFileSync(path.resolve(import.meta.dirname, '../features/tests/model/testsDashboard.ts'), 'utf8');
const ru = JSON.parse(readFileSync(path.resolve(import.meta.dirname, '../locales/ru/translation.json'), 'utf8'));
const kk = JSON.parse(readFileSync(path.resolve(import.meta.dirname, '../locales/kk/translation.json'), 'utf8'));

assert.ok(existsSync(viewPath), 'Desktop tests dashboard view should be feature-local');
assert.match(page, /getTestsDashboard/);
assert.match(page, /<TestsHubView[\s\S]*dashboard=/);
assert.match(page, /status=\{status\}/);
assert.match(view, /analyzeStatus/);
assert.match(view, /const dashboardReady = status === 'ready' && dashboard !== null/);
assert.match(view, /const showStatisticsEmpty = status === 'ready' && dashboard !== null && statisticsVisibility\.showEmpty/);
assert.match(optionCard, /aria-disabled(?:=|['"])/);
assert.match(view, /data-tests-mode-grid/);
assert.match(view, /min-h-\[196px\]/);
assert.match(view, /function ChapterCardSkeleton\(\)/, 'chapter loading must use a feature-local skeleton component');
assert.match(view, /data-tests-chapter-skeleton[\s\S]*h-\[196px\][\s\S]*rounded-\[16px\][\s\S]*bg-white[\s\S]*p-6/, 'chapter skeleton must match the real card outer anatomy');
assert.match(view, /data-tests-chapter-skeleton[\s\S]*data-tests-chapter-skeleton-metric[\s\S]*data-tests-chapter-skeleton-title[\s\S]*data-tests-chapter-skeleton-questions/, 'chapter skeleton must expose visible metric, title, and question placeholders');
assert.match(view, /Array\.from\(\{ length: 6 \}[\s\S]*<ChapterCardSkeleton/, 'loading must keep six chapter skeletons in the existing grid');
assert.match(view, /data-tests-mode-card="mock"[\s\S]*status === 'loading' \? <ModeCardSkeleton \/>/, 'the fixed mock slot must skeletonize only while the dashboard loads');
assert.match(view, /data-tests-mode-skeleton/, 'every loading mode card must expose the shared skeleton marker');
assert.match(view, /data-tests-right-column/);
assert.match(view, /data-tests-mode-card="mock"/);
assert.match(optionCard, /to\?: string/, 'option-card navigation must be an explicit destination contract');
assert.doesNotMatch(optionCard, /available\?: boolean/, 'test availability must not be conflated with surface interaction');
assert.match(optionCard, /if \(!to\)/, 'a card without a destination must render a disabled surface');
assert.match(optionCard, /<Link[\s\S]*to=\{to\}/, 'the root link must consume the explicit destination without route inference');
assert.match(view, /to=\{dashboardReady && modeAvailability\(dashboard, 'random'\)\?\.available === true \? '\/tests\/random' : undefined\}/);
assert.match(view, /analyzeStatus === 'empty'[\s\S]*to="\/analyze"[\s\S]*contract="weak-pre-analysis"/);
assert.match(view, /const weakAvailable = modeAvailability\(dashboard, 'weak'\)\?\.available === true/);
assert.match(view, /weakAvailable \? <DesktopTestOptionCard[\s\S]*to="\/tests\/weak"/);
assert.match(view, /weakAvailable \? [\s\S]*: analyzeStatus === 'empty'/);
assert.doesNotMatch(view, /reason\?\.message/, 'server English availability messages must not leak into the UI');
assert.match(view, /reason\?\.reason === 'no_weak_chapters'[\s\S]*t\('tests\.desktopWeakUnavailableNoAnalyze'/);
assert.match(view, /reason\?\.reason === 'insufficient_question_pool'[\s\S]*t\('tests\.desktopInsufficientPool'/);
assert.doesNotMatch(optionCard, /cursor-not-allowed/);
assert.match(chapterCard, /\{\.\.\.\(metric \? \{ 'data-chapter-metric': metric \} : \{\}\)\}/, 'metric state must be exposed through the conditional data attribute spread');
assert.match(chapterCard, /data-chapter-navigation/, 'title and question navigation must have a dedicated non-overlapping hit target');
assert.match(chapterCard, /aria-describedby=/, 'metric focus targets must expose their tooltip as an accessible description');
assert.doesNotMatch(chapterCard, /a11y:\s*\{\s*test:\s*'todo'/, 'chapter-card stories must not downgrade all axe failures to warnings');
assert.match(chapterCard, /metric="accuracy"/);
assert.match(chapterCard, /metric="delta"/);
assert.match(chapterCard, /data-chapter-title/);
assert.match(chapterCard, /group-hover:opacity-100/);
assert.doesNotMatch(chapterCard, /cardClassName = `group/);
assert.match(view, /deltaTone/);
assert.match(view, /delta > 0 \? ChartUpIcon : ChartDownIcon/);
assert.match(chapterCard, /chapter\.deltaPoints !== null && chapter\.deltaPoints > 0/);
assert.match(chapterCard, /isChapterLaunchAvailable/);
assert.match(chapterCard, /aria-disabled=\{available \? undefined : 'true'\}/);
assert.match(chapterCard, /data-chapter-available=\{available \? 'true' : 'false'\}/);
assert.match(chapterCard, /h-\[196px\]/, 'chapter cards must keep the exact 320x196 Figma surface');
assert.match(chapterCard, /data-chapter-no-data[\s\S]*text-\[14px\][\s\S]*leading-\[14px\]/, 'no-data badge must use exact 14px typography');
assert.match(chapterCard, /metric="accuracy"[\s\S]*text-\[14px\][\s\S]*leading-\[14px\]/, 'accuracy badge must use exact 14px typography');
assert.match(chapterCard, /data-chapter-title[\s\S]*text-\[16px\][\s\S]*leading-4/, 'chapter title must use exact 16px typography');
assert.match(chapterCard, /data-chapter-question-count[\s\S]*text-\[14px\][\s\S]*leading-\[14px\]/, 'question count must use exact 14px typography');
assert.match(chapterCard, /h-\[102px\]/, 'chapter card content must keep the exact 102px Figma height');
assert.match(chapterCard, /data-chapter-question-count[\s\S]*className="mt-auto/, 'question count must be bottom-anchored for every title length');
assert.match(chapterCard, /HugeiconsIcon[\s\S]*icon=\{ChartUpIcon\}[\s\S]*size=\{20\}/, 'delta must render the selected 20px HugeIcons glyph');
assert.match(chapterCard, /deltaPoints > 0[\s\S]*-scale-x-100/, 'positive deltas must mirror the source glyph');
assert.match(chapterCard, /metric="delta"[\s\S]*ChartUpIcon[\s\S]*formatDelta/, 'the delta metric target must wrap both the icon and value');
assert.doesNotMatch(chapterCard, /trending-up\.svg|mask-image|MaskImage/, 'the migrated delta glyph must not retain an SVG mask');
assert.match(story, /questionCount: 0/);
assert.match(view, /text-\[#29ae70\]/);
assert.match(view, /text-\[#bc251a\]/);
assert.match(view, /bg-\[#efeaf8\]/);
assert.match(view, /grid-cols-\[minmax\(0,1fr\)_320px\]/, 'dashboard must reserve an exact 320px right column for Figma panels');
assert.match(view, /rounded-\[16px\]/);
assert.match(view, /tests\.desktopShowMore/);
assert.match(view, /data-tests-chapters-grid/, 'chapter cards and show-more must share one responsive grid');
assert.match(view, /col-span-2[\s\S]*data-tests-desktop-show-more/, 'show-more must span exactly two chapter columns');
assert.match(view, /data-tests-desktop-show-more/, 'show-more must expose a focused browser contract marker');
assert.match(view, /transition-colors[\s\S]*hover:bg-\[#d4c4ea\][\s\S]*hover:text-\[#6f45b6\]/, 'show-more hover must use the approved calmer saturated palette');
assert.match(view, /focus-visible:bg-\[#d4c4ea\][\s\S]*focus-visible:text-\[#6f45b6\]/, 'show-more keyboard focus must share hover color feedback');
assert.match(view, /group-hover:translate-y-0\.5[\s\S]*group-focus-visible:translate-y-0\.5/, 'show-more chevron must shift down subtly on hover and keyboard focus');
assert.match(view, /data-tests-desktop-show-more[\s\S]*transition-transform/, 'show-more chevron must transition its transform');
assert.doesNotMatch(view, /w-\[655\.34px\]/, 'show-more width must not be hardcoded');
assert.doesNotMatch(view, /<h1[^>]*>.*РўРµСЃС‚/);

assert.ok(existsSync(optionStoryPath), 'isolated weak/mock option-card stories should exist');
assert.match(optionCard, /HugeiconsIcon[\s\S]*Target03Icon[\s\S]*LockKeyIcon/);
assert.doesNotMatch(optionCard, /target-03\.svg|lock-keyhole\.svg/);
assert.match(optionCard, /data-option-card-contract=\{contract\}/);
assert.match(optionStory, /contract: 'weak-pre-analysis'/);
assert.match(optionStory, /contract: 'mock-inactive'/);
assert.match(optionCard, /size-12[\s\S]*rounded-\[8px\]/);
assert.match(optionCard, /gap-6[\s\S]*px-6[\s\S]*pb-8[\s\S]*pt-6/);
assert.doesNotMatch(optionCard, /unavailableAction/);
assert.match(view, /analyzeStatus === 'empty'/);
assert.match(view, /contract="mock-inactive"/);
assert.doesNotMatch(view, /mode="mock"[\s\S]{0,400}to=/, 'mock mode must remain non-navigable');
assert.match(optionStory, /to: '\/analyze'/);
assert.match(optionStory, /w-\[320px\][\s\S]*h-\[196px\]/);
assert.match(optionStory, /w-\[655px\][\s\S]*h-\[180px\]/);
assert.match(story, /DesktopAnalyzeError/);
assert.match(story, /DesktopErrorWithStaleDashboard/);
assert.match(story, /DesktopCatalogWithStaleDashboard/);
assert.match(story, /useLocation/);
assert.match(story, /data-location-pathname/);
assert.match(story, /data-location-url/);
assert.match(story, /getByRole\('link'[\s\S]*\/analyze/);
assert.match(story, /keyboard\('\{Enter\}'\)/);
assert.match(story, /userEvent\.tab\(\)[\s\S]*recentLink[\s\S]*toHaveFocus/);
assert.match(story, /DesktopRecentMouseNavigation[\s\S]*userEvent\.click\(recentLink\)[\s\S]*\/tests\/random\?attemptRef=attempt-1/);
assert.match(story, /userEvent\.click\(weakCard\)/);
assert.match(story, /a\[href="\/tests\/weak"\]/);
assert.match(story, /DesktopZeroAttempts[\s\S]*completedAttemptCount: 0/, 'page-level zero-attempt story must expose the empty panels');
assert.match(story, /DesktopLegacyMissingCounts[\s\S]*completedAttemptCount: null[\s\S]*overallAccuracy: null[\s\S]*overallDeltaPoints: null/, 'page-level legacy story must expose missing-count empty panels');
assert.match(story, /DesktopError[\s\S]*data-tests-statistics-empty[\s\S]*data-tests-statistics-spacer/, 'dashboard error story must reject inferred empty statistics');

assert.ok(existsSync(chapterStoryPath), 'isolated chapter-card stories should exist');
assert.match(chapterStory, /<MemoryRouter>/);
assert.match(chapterStory, /w-\[320px\][\s\S]*h-\[196px\]/);
assert.match(chapterStory, /export const NoTest/);
assert.match(chapterStory, /export const LegacyNoTest/);
assert.match(chapterStory, /export const FirstTest/);
assert.match(chapterStory, /export const Full/);
assert.match(chapterStory, /export const ShortTitle/);
assert.match(chapterStory, /Системы счисления/);
assert.match(chapterStory, /export const ShortTitle/);
assert.match(chapterStory, /Системы счисления/);
assert.match(chapterStory, /Современные тенденции развития информационных технологий\. IT Startup \(ай-ти-стартап\)\. 3D моделирования/);
assert.match(chapterStory, /64 вопроса/);
assert.doesNotMatch(chapterStory, /test:\s*'todo'/, 'exact-card stories must keep accessibility failures blocking');
assert.match(chapterStory, /test:\s*'error'/);
assert.match(chapterStory, /rules:\s*\[\{ id:\s*'color-contrast', enabled:\s*false \}\]/, 'only exact-reference color contrast may be excluded');
assert.match(chapterStory, /expectCardTabOrder/);
assert.match(chapterStory, /toHaveFocus/);
assert.doesNotMatch(story, /test:\s*'todo'/, 'hub stories must not downgrade all axe failures to warnings');
assert.match(story, /test:\s*'error'/);
assert.match(story, /rules:\s*\[\{ id:\s*'color-contrast', enabled:\s*false \}\]/, 'hub stories may exclude only the mandated palette contrast rule');

assert.equal(ru.tests.desktopWeakBadge, 'После анализа ЕНТ');
assert.equal(ru.tests.desktopWeakDescription, 'Подборка вопросов по разделам, где вы теряете баллы');
assert.equal(ru.tests.desktopMockBadge, 'В процессе разработки');
assert.equal(ru.tests.desktopMockTitle, 'Пробный тест');
assert.equal(ru.tests.desktopMockDescription, 'Подборка из 40 вопросов в формате настоящего ЕНТ');
assert.equal(ru.tests.desktopNoData, 'Нет данных');
assert.equal(ru.tests.desktopStatisticsEmptyTitle, 'Общая точность появится здесь');
assert.equal(ru.tests.desktopStatisticsEmptyBody, 'после первого теста');
assert.equal(ru.tests.desktopRecentEmptyTitle, 'История тестов появится здесь');
assert.equal(ru.tests.desktopRecentEmptyBody, 'после первого теста');
assert.equal(kk.tests.desktopWeakBadge, 'ҰБТ талдауынан кейін');
assert.equal(kk.tests.desktopWeakDescription, 'Балл жоғалтатын бөлімдер бойынша сұрақтар жинағы');
assert.equal(kk.tests.desktopMockBadge, 'Әзірлену үстінде');
assert.equal(kk.tests.desktopMockTitle, 'Сынақ тесті');
assert.equal(kk.tests.desktopMockDescription, 'Нағыз ҰБТ форматындағы 40 сұрақтан тұратын жинақ');
assert.equal(kk.tests.desktopNoData, 'Деректер жоқ');
assert.equal(kk.tests.desktopStatisticsEmptyTitle, 'Жалпы дәлдік осы жерде пайда болады');
assert.equal(kk.tests.desktopStatisticsEmptyBody, 'бірінші тесттен кейін');
assert.equal(kk.tests.desktopRecentEmptyTitle, 'Тесттер тарихы осы жерде пайда болады');
assert.equal(kk.tests.desktopRecentEmptyBody, 'бірінші тесттен кейін');

assert.match(view, /getDashboardMetricVisibility/);
assert.match(view, /data-tests-statistics-empty/);
assert.match(view, /className="h-7 w-\[67px\]" data-tests-statistics-spacer/, 'empty statistics heading must reserve the exact 67x28 spacer');
assert.match(view, /data-tests-statistics-accuracy/);
assert.match(view, /data-tests-statistics-delta/);
assert.match(view, /className="flex w-full flex-col gap-1 px-2" data-tests-recent-empty/);
assert.match(view, /desktopRecentEmptyTitle/);
assert.match(view, /desktopRecentEmptyBody/);
assert.match(view, /<Link[\s\S]*to=\{`\/tests\/\$\{recent\.mode\}\?attemptRef=\$\{encodeURIComponent\(recent\.attemptRef\)\}`\}/, 'every recent row must be a native attempt link');
assert.match(view, /formatRecentTestDateTime\(recent\.completedAt, locale\)/, 'recent rows must show localized local date and time');
assert.doesNotMatch(view, /recent\.displayDate|toLocaleDateString/, 'legacy displayDate and date-only formatting must not drive the desktop UI');
assert.match(dashboardModel, /new Intl\.DateTimeFormat\(locale === 'kk' \? 'kk-KZ' : 'ru-RU', \{[\s\S]*day: 'numeric',[\s\S]*month: 'short',[\s\S]*hour: '2-digit',[\s\S]*minute: '2-digit',/, 'recent dates must use locale-aware day, short month, hour, and minute fields');
assert.doesNotMatch(dashboardModel, /dateStyle: 'medium'|timeStyle: 'short'/, 'recent dates must not include the year through dateStyle or timeStyle');
assert.match(view, /role="tooltip"/);
assert.match(view, /aria-describedby=\{tooltipId\}/);
assert.match(view, /useId\(\)/);
assert.match(view, /group-hover:opacity-100[\s\S]*group-focus-within:opacity-100/);
assert.match(view, /focus-visible:outline/);
assert.match(view, /incorrectAnswerCount/);
assert.match(view, /skippedQuestionCount > 0/);
assert.match(view, /desktopRecentOpenHint/);
const recentLinkSource = view.match(/<Link[\s\S]*?<\/Link>/)?.[0] ?? '';
assert.doesNotMatch(recentLinkSource, /<button/, 'recent links must not contain nested interactive controls');
assert.equal(ru.tests.desktopRecentCorrect, 'Правильные ответы: {{count}}');
assert.equal(ru.tests.desktopRecentIncorrect, 'Неправильные ответы: {{count}}');
assert.equal(ru.tests.desktopRecentSkipped, 'Пропущено: {{count}}');
assert.equal(ru.tests.desktopRecentOpenHint, 'Нажмите, чтобы открыть результат');
assert.equal(kk.tests.desktopRecentCorrect, 'Дұрыс жауаптар: {{count}}');
assert.equal(kk.tests.desktopRecentIncorrect, 'Қате жауаптар: {{count}}');
assert.equal(kk.tests.desktopRecentSkipped, 'Өткізілді: {{count}}');
assert.equal(kk.tests.desktopRecentOpenHint, 'Нәтижені ашу үшін басыңыз');
assert.match(view, /desktopSortImportance[\s\S]*defaultValue: 'По значимости раздела'/, 'Russian sort labels should remain readable in the trigger fallback');
assert.match(view, /desktopSortCount[\s\S]*defaultValue: 'По количеству вопросов'/, 'Russian count sort label should remain readable');
assert.match(view, /desktopSortAccuracy[\s\S]*defaultValue: 'По точности ответов пользователя'/, 'Russian accuracy sort label should remain readable');
assert.match(view, /\['importance', 'count', 'accuracy'\]/, 'Desktop sort options should follow importance, count, accuracy order');
for (const marker of ['Рџ', 'РІ', 'Рѕ', 'Рµ', 'С‚', 'СЃ']) {
  assert.doesNotMatch(view, new RegExp(marker), `Desktop Tests view must not contain mojibake marker ${marker}`);
}
assert.match(chapterCard, /getChapterMetricVisibility/);
assert.match(chapterCard, /data-chapter-no-data/);
assert.match(chapterCard, /metricVisibility\.showAccuracy/);
assert.match(chapterCard, /metricVisibility\.showDelta/);

console.log('Desktop tests Figma contract passed');
